//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeScanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class HID
    {
        public int HIDId { get; set; }
        public string HID1 { get; set; }
    }
}
